# Generated by Django 5.2.15 on 2026-06-14 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('kind', models.CharField(choices=[('toy', 'Іграшки'), ('home', 'Для дому')], default='toy', max_length=10, verbose_name='Світ')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='Надзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показувати')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140, verbose_name="Ім'я та прізвище")),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('delivery', models.CharField(choices=[('np-branch', 'Нова Пошта — відділення'), ('np-courier', "Нова Пошта — кур'єр"), ('pickup', 'Самовивіз')], default='np-branch', max_length=20, verbose_name='Доставка')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Місто')),
                ('branch', models.CharField(blank=True, max_length=120, verbose_name='Відділення / поштомат')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('payment', models.CharField(choices=[('online', 'Картка онлайн'), ('cod', 'Накладений платіж')], default='online', max_length=20, verbose_name='Оплата')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('shipping', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Доставка, ₴')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Разом, ₴')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('processing', 'В обробці'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('meta', models.CharField(blank=True, help_text='Напр.: «26 см · вершковий»', max_length=120, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Ціна, ₴')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, help_text='Для перекресленої ціни', max_digits=8, null=True, verbose_name='Стара ціна, ₴')),
                ('badge', models.CharField(blank=True, choices=[('', '—'), ('Хіт', 'Хіт'), ('Новинка', 'Новинка'), ('Великий', 'Великий')], default='', max_length=12, verbose_name='Бейдж')),
                ('sizes', models.CharField(blank=True, help_text='Через кому: 18 см, 22 см, 26 см', max_length=200, verbose_name='Розміри')),
                ('colors', models.CharField(blank=True, help_text='Через кому, формат «назва:#HEX»: вершковий:#EFE7D7, сірий:#B7BCC0', max_length=300, verbose_name='Кольори')),
                ('placeholder', models.CharField(choices=[('bunny', 'Зайчик'), ('hanging', 'Кашпо підвісне'), ('woven', 'Кашпо плетене'), ('chain', 'Кашпо на ланцюжку')], default='bunny', max_length=12, verbose_name='SVG-балванка')),
                ('color1', models.CharField(default='#C5806C', max_length=7, verbose_name='Колір SVG (світлий)')),
                ('color2', models.CharField(default='#A4604D', max_length=7, verbose_name='Колір SVG (темний)')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Відгуків')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='Очікується')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Назва')),
                ('options', models.CharField(blank=True, max_length=200, verbose_name='Опції')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Ціна, ₴')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=140, verbose_name='Опис (alt)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
                'ordering': ['-is_main', 'order', 'id'],
            },
        ),
    ]
