# Generated by Django 5.2.15 on 2026-06-14 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_created_alter_product_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True, verbose_name='Ref')),
                ('name', models.CharField(db_index=True, max_length=160, verbose_name='Назва')),
                ('area', models.CharField(blank=True, max_length=160, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'НП: місто',
                'verbose_name_plural': 'НП: міста',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref міста НП'),
        ),
        migrations.AddField(
            model_name='order',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref відділення НП'),
        ),
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.CharField(blank=True, max_length=255, verbose_name='Відділення / поштомат'),
        ),
        migrations.CreateModel(
            name='NPWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True, verbose_name='Ref')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер')),
                ('description', models.CharField(max_length=255, verbose_name='Назва/адреса')),
                ('short_address', models.CharField(blank=True, max_length=255, verbose_name='Коротка адреса')),
                ('category', models.CharField(blank=True, max_length=40, verbose_name='Категорія НП')),
                ('is_poshtomat', models.BooleanField(default=False, verbose_name='Поштомат')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Довгота')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='shop.npcity', verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'НП: відділення',
                'verbose_name_plural': 'НП: відділення',
                'ordering': ['city__name', 'number'],
                'indexes': [models.Index(fields=['city', 'is_poshtomat'], name='shop_npware_city_id_8384c6_idx')],
            },
        ),
    ]
