# Generated by Django 5.2.15 on 2026-06-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_npcity_order_np_city_ref_order_np_warehouse_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL фото (Cloudinary)'),
        ),
    ]
