# Generated by Django 5.2.15 on 2026-06-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_productimage_image_productimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Залиште порожнім — згенерується з назви (латиницею).', max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Залиште порожнім — згенерується з назви (латиницею).', max_length=160, unique=True, verbose_name='Slug'),
        ),
    ]
