"""
Django settings for klubok project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Локальні налаштування (DATABASE_URL, ключі) — з файлу .env, якщо він є.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# У проді задайте змінну оточення DJANGO_SECRET_KEY; фолбек — лише для розробки.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-87ele1o5bcfd-2_c)p-srt38x@7l%n_t+!kt-(b#3oqx#n77%)',
)

# SECURITY WARNING: don't run with debug turned on in production!
# У проді: DJANGO_DEBUG=0
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']
# У проді додайте домен: DJANGO_ALLOWED_HOSTS=klubok.ua,www.klubok.ua
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',          # блокування перебору пароля
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',   # має бути останнім
]

# django-axes: спершу перевіряє блокування, потім звичайна автентифікація
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'klubok.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart',
                'shop.context_processors.nav_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'klubok.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Якщо задано змінну оточення DATABASE_URL — використовуємо її (PostgreSQL),
# інакше — локальний SQLite. Той самий код працює і локально, і в хмарі.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'Europe/Kyiv'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Uploaded media (product photos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session-based cart
CART_SESSION_ID = 'cart'
# Shop business rules (mirrors the prototype)
FREE_SHIPPING_FROM = 800        # ₴ — free delivery threshold
SHIPPING_OPTIONS = {            # delivery method -> price (₴)
    'np-branch': 70,
    'np-courier': 110,
    'pickup': 0,
}

# Нова Пошта. Ключ краще тримати в змінній оточення NOVA_POSHTA_API_KEY;
# фолбек — наданий бізнес-ключ (рекомендується перевипустити в кабінеті НП).
NOVA_POSHTA_API_KEY = os.environ.get(
    'NOVA_POSHTA_API_KEY', '615ba552a4b1e3a83a1faf31bd04a964'
)
NOVA_POSHTA_API_URL = 'https://api.novaposhta.ua/v2.0/json/'

# Пошта. Якщо задано EMAIL_HOST_USER + EMAIL_HOST_PASSWORD (Gmail App Password) —
# листи йдуть через SMTP Gmail; інакше друкуються в консоль (зручно для розробки).
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# App Password Google показує з пробілами — прибираємо їх (інакше SMTP-логін не пройде)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').replace(' ', '')
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_TIMEOUT = 15

# Від кого листи й куди слати сповіщення про нові замовлення
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Клубок <handmakesite@gmail.com>')
ORDER_NOTIFY_EMAIL = os.environ.get('ORDER_NOTIFY_EMAIL', 'handmakesite@gmail.com')

# Cloudinary — зберігання й обробка фото товарів (фото НЕ зберігаються локально).
import cloudinary  # noqa: E402

cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    api_key=os.environ.get('CLOUDINARY_API_KEY', ''),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET', ''),
    secure=True,
)

# --- django-axes: захист від перебору пароля ---
AXES_FAILURE_LIMIT = 5             # дозволених невдалих спроб
AXES_COOLOFF_TIME = 1              # блокування на 1 годину
AXES_RESET_ON_SUCCESS = True       # лічильник скидається після успішного входу
AXES_LOCKOUT_PARAMETERS = ['ip_address']   # блокуємо за IP
AXES_LOCKOUT_TEMPLATE = None       # повертає стандартну 429-відповідь

# Адреса адмінки. У проді задайте свою неочевидну: DJANGO_ADMIN_URL=secret-panel/
ADMIN_URL = os.environ.get('DJANGO_ADMIN_URL', 'admin/')

# --- Безпека для продакшену (активна лише коли DEBUG=False) ---
if not DEBUG:
    SECURE_SSL_REDIRECT = True                               # http -> https
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # за reverse-proxy (Render тощо)
    SESSION_COOKIE_SECURE = True                            # cookies лише через https
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000                          # рік
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True                      # проти MIME-sniffing
    X_FRAME_OPTIONS = 'DENY'                                # проти clickjacking
    # Дозволені джерела для CSRF (ваш домен): CSRF_TRUSTED_ORIGINS=https://klubok.ua
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
